// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from '@/types/supabase';

const SUPABASE_URL = "https://oroxuwimqurrxqrxvlmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yb3h1d2ltcXVycnhxcnh2bG14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MTgwNzksImV4cCI6MjA1OTE5NDA3OX0.kKOeNNivJzQ8urgCmOImtmBCp77EqyFXsIM4oSYwnFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);